version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "06:20"
      timezone: Europe/Zurich

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "06:20"
      timezone: Europe/Zurich
