name: Release

on:
  release:
    types: [created]

env:
  DOTNET_VERSIONS: |
    6.0.x
    7.0.x

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSIONS }}

      - name: Create NuGet Package
        run: |
          dotnet pack TeaSuite.KV.sln --configuration Release
          mkdir packages/ || true
          cp $(find ./ -name *.nupkg -print) packages/

      - name: Publish NuGet Package
        run: |
          dotnet nuget push packages/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
